# Generated by Django 3.0.7 on 2020-06-08 21:19

import django.core.serializers.json
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('target_uuid', models.UUIDField()),
                ('author_uuid', models.UUIDField()),
                ('text', models.TextField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_ts',
            },
        ),
        migrations.CreateModel(
            name='CommentView',
            fields=[
                ('view_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment_uuid', models.UUIDField()),
                ('viewer_uuid', models.UUIDField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_ts',
            },
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('operation_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('operation_name', models.TextField()),
                ('source', models.TextField()),
                ('source_version', models.TextField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(verbose_name=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'get_latest_by': 'created_ts',
            },
        ),
    ]
